### PR TITLE
reverse changes to the response object from last commit

### LINKED ISSUE #30: hydra-cli rest command displays error when response is JSON
Following https://community.risingstack.com/tutorial-building-expressjs-based-microservices-using-hydra/ and replacing "fwsp-hydra-express" with "hydra-express"

When I use hydra-cli to try the REST service "hello", the hydra-cli will only show normal output if the REST service returns a string. If the REST service returns a JSON object, hydra-cli returns the following error:
Cannot read property 'toString' of undefined

### PR DESCRIPTION
**Pull request by juxe**
reverse changes to the response object from last commit, to fix #30

### CODE REVIEW

**Review by c35xr — APPROVED** [review]

**Comment by c35xr** [comment]
Oh men I can't believe that this PR has almost 2 years open, I start today trying to use this lib, and found the same opportunity.

**Comment by cjus** [comment]
Whats the issue you're running into?

**Comment by c35xr** [comment]
When I send an object as response, the handleRest to be more specific in the line  527, the promise `hydra.makeAPIRequest(msg)` returns a res object without payLoad, the line 529 try to converts  to string over a params that not exists, `res.payLoad.toString('utf8');` and throw an error,  I not sure if this is related with the line 1289 on hidra, https://github.com/flywheelsports/hydra/blob/8277a05ea181fbc0338a90889d831277add8bddd/index.js#L1289, but deleting the lines on this PR solves the error on hidra-cli.

**Comment by JustusFluegel** [comment]
PLEASE merge this pr, it's just anoying like it is now. :)

**Comment by JustusFluegel** [comment]
If no one wants to maintain this project anymore, please give rights to someone who wants to do so, as it's just not productive like that anymore.

**Comment by cjus** [comment]
@Technikkeller I'll review this PR this weekend.

**Pull request closed without merging**
